### ISSUE TITLE
Accuracy of evaluation results using negative sampling

### ISSUE THREAD

**Issue by MatthiasEg** [THUwangcy/ReChorus#45]
Hi,

thank you for your work!
I read through your code and trained a few models on my dataset (#users 45'000, #items 260'000) using your library and have a question for which I would greatly appreciate your thoughts.

I have the feeling that evaluation results for evaluations using negative sampling are overly confident and do not reflect the actual performance of a model on a dataset. Let's say we have 99 negative samples and add the ground truth label, then the model must only differentiate between 100 classes instead of e.g. 260'000, and can even be sure that the actual class is part of these 100. This approach, IMO, greatly simplifies the task at hand. If that assumption is correct, what is even the point of this strategy (apart from lower computational efficiency)?

Also, would you mind explaining what the below code should do. From my understanding, this piece of code prevents proper evaluation on all the items, because it adjusts what the model has actually predicted.

```python
if dataset.model.test_all:
    rows, cols = list(), list()
    for i, u in enumerate(dataset.data['user_id']):
        clicked_items = list(dataset.corpus.train_clicked_set[u] | dataset.corpus.residual_clicked_set[u])
        idx = list(np.ones_like(clicked_items) * i)
        rows.extend(idx)
        cols.extend(clicked_items)
    predictions[rows, cols] = -np.inf
```

Thank you!

**Comment by THUwangcy** [comment]
This sampling-based evaluation has its roots in the paper [NCF](https://dl.acm.org/doi/pdf/10.1145/3038912.3052569), and it has been widely adopted in subsequent studies. We also use this evaluation setting mainly because it is widely acknowledged and computationally efficient. 

However, it indeed has limitations as discussed by Rendle in [this paper](https://dl.acm.org/doi/pdf/10.1145/3394486.3403226). To address this, we add the --test_all parameter to support the all-ranking evaluation protocol. 

As for the codes you mention, it is crucial to understand that the all-ranking evaluation setting doesn't rank all items but rather focuses on items that the user has not interacted with. To achieve this, the code sets the prediction results of items that the user has already interacted with to a very low value (-inf). This ensures that these items will be pushed to the lower end of the ranking, guaranteeing that the top-ranked items are those the user has not previously interacted with.

**Comment by MatthiasEg** [comment]
Thank you for your answer.

> As for the codes you mention, it is crucial to understand that the all-ranking evaluation setting doesn't rank all items but rather focuses on items that the user has not interacted with. To achieve this, the code sets the prediction results of items that the user has already interacted with to a very low value (-inf). This ensures that these items will be pushed to the lower end of the ranking, guaranteeing that the top-ranked items are those the user has not previously interacted with.

Such a feature I would personally expect under a different parameter, like "--recommend_historic_items", because it doesn't really have anything to do with the basic idea of "--test_all". Or am I misunderstanding something?

**Comment by THUwangcy** [comment]
I think it is generally acknowledged that recommendation results should exclude historic items in the literature (except for some studies focused on repeat consumption). Notice that it is also usually referred to as "all-ranking" protocol in related [papers](https://arxiv.org/pdf/2002.02126.pdf).

> The evaluation metrics are recall@20 and ndcg@20 computed by the all-ranking protocol — all items that are not interacted by a user are the candidates.

However, this may indeed lead to some misunderstandings for newcomers. We will consider enriching the explanation of this parameter or changing its name.
