### ISSUE TITLE
Questions about the paper

### ISSUE THREAD

**Issue by Inferior-Gentleman** [THUwangcy/ReChorus#7]
Nice paper which inspires me a lot ! But I still have two questions: 

1. Why ReChorus need the categories information？
2. How do you get the relations like “complment” or “substitute” between the items？The original Amazon review data just list the relations like “buy after viewing” or  “also bought_together”.

Thank you for replying

**Comment by THUwangcy** [comment]
Thanks for your interest! With regard to the questions:

1. The categories information is used in the design of temporal kernel functions. As illustrated in Section 5.5, even for the same relation type, the temporal evolution of relational effects may differ from each other, which reflects the characteristics of different items. We do not estimate item-specific parameters because this may suffer from the data sparsity issue (If categories information is not provided, global or item-specific parameters are also feasible).
2. As stated in Section 5.1.1, we follow previous researches to take "also_view" as substitutes and "also_buy" as complement relation.

Hope this helps.
